parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: common
        connections:
            common:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL_COMMON)%'
    orm:
        default_entity_manager: common
        entity_managers:
            common:
                connection: common
                mappings:
                    Common:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Common/Entity'
                        prefix: 'App\Common\Entity'
                        alias: Common
