api_common:
    resource: ../../src/Common/Actions/API
    type: annotation
    prefix: /api/common

web_common:
    resource: ../../src/Common/Actions/Web
    type: annotation

api_login_check:
    path: /api/login_check
