api_common:
    resource: ../../src/Actions/API
    type: annotation
    prefix: /api

web_common:
    resource: ../../src/Actions/Web
    type: annotation

api_login_check:
    path: /api/login_check
